USE_CAMERA_STUB := true

TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Platform
TARGET_BOARD_PLATFORM := exynos3475

# Architecture
TARGET_ARCH := arm
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

BOARD_VENDOR := samsung
TARGET_BOOTLOADER_BOARD_NAME := universial3475
TARGET_BOOTLOADER_BOARD_NAME := novel3gskt

# Kernel
TARGET_KERNEL_CONFIG := exynos3475-novellte_defconfig
TARGET_KERNEL_SOURCE := kernel/samsung/exynos3475

BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# Filesystem
BOARD_BOOTIMAGE_PARTITION_SIZE := 13631488
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 15728640
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 2254438400
BOARD_USERDATAIMAGE_PARTITION_SIZE := 5150605312
BOARD_CACHEIMAGE_PARTITION_SIZE := 209715200
BOARD_FLASH_BLOCK_SIZE := 131072
TARGET_USERIMAGES_USE_EXT4 := true

TARGET_RECOVERY_INITRC := device/samsung/novel3gskt/init.rc
BOARD_HAS_NO_SELECT_BUTTON := true

# inherit from the proprietary version
-include vendor/samsung/noveltekx/BoardConfigVendor.mk
